export const refs = {
  cocktailsList: document.querySelector('.cocktails-list'),
  cocktailsTitle:document.querySelector(".cocktails-section-title"),
  learnMoreBtn: document.querySelector('.learn-more'),
  favBtn: document.querySelector('.fav-btn'),
  modalCocktail: document.querySelector('.modal-cocktail'),
  modalIngredient: document.querySelector('.modal-ing-container'),
  modal: document.querySelector('.modal-cockt-container'),
  listCocktail: document.querySelector('.modal-ingredients__list'),
  favCocktailsList :document.querySelector(".fav-cocktails-list"),
  errorDiv:document.querySelector(".error"),
  ingredientsList: document.querySelector(".fav-ing-list"),
  favTitle: document.querySelector(".fav-title"),
  searchField: document.querySelector(".search-form__input"),
  alphabet: document.querySelector(".custom-list"),
  burgerMenu: document.querySelector('.header-menu'),
  modalBurger: document.querySelector('.modal-burger-container'),
  headerLinkFav: document.querySelector(".header-nav-link-fav"),
  favMenu: document.querySelector(".header-favorite-menu"),
  select: document.querySelector('.custom-list-select'),
  dropDownList: document.querySelector(".drop-down__list"),
  alcoholic: document.querySelector(".alco-title"),
  viewCoctailsBtn: document.querySelector(".cocktails-btn"),
  body: document.body,
};

