export const refs = {
  alphabet: document.querySelector('.custom-list'),
  select: document.querySelector('.custom-list-select'),
  alcoholic: document.querySelector('.alco-title'),
  body: document.body,
  burgerMenu: document.querySelector('.header-menu'),
  btnPaginationBlock: document.querySelector('.pagination-block'),
  btnPaginationNext: document.querySelector("#pagination-btn-next"),
  btnPaginationPrev: document.querySelector("#pagination-btn-prev"),
  cocktailsList: document.querySelector('.cocktails-list'),
  cocktailsTitle: document.querySelector('.cocktails-section-title'),
  dropDownList: document.querySelector('.drop-down__list'),
  errorDiv: document.querySelector('.error'),
  favBtn: document.querySelector('.fav-btn'),
  favCocktailsList: document.querySelector('.fav-cocktails-list'),
  favMenu: document.querySelector('.header-favorite-menu'),
  favTitle: document.querySelector('.fav-title'),
  headerLinkFav: document.querySelector('.header-nav-link-fav'),
  ingredientsList: document.querySelector('.fav-ing-list'),
  learnMoreBtn: document.querySelector('.learn-more'),
  listCocktail: document.querySelector('.modal-ingredients__list'),
  modal: document.querySelector('.modal-cockt-container'),
  modalBurger: document.querySelector('.modal-burger-container'),
  modalCocktail: document.querySelector('.modal-cocktail'),
  modalIngredient: document.querySelector('.modal-ing-container'),
  paginationBtn: document.querySelector('.pagination-page'),
  paginationContainer: document.querySelector('.pagination-container'),
  searchField: document.querySelector('.search-form__input'),
  viewCoctailsBtn: document.querySelector('.cocktails-btn'),
};

export const refsDark = {
    
    // herotitle: document.querySelector('.hero-title'), 
    // herotext: document.querySelector('.hero-text'), 
    // iconHeroStarOne: document.querySelector('.icon-hero-star-one '),
    // iconHeroStarTwo: document.querySelector('.icon-hero-star-two'),
    // heroImgText : document.querySelector('.hero-img-text'),
    // modalCocktailTextWrapperDarkH1: document.querySelector('.modal-cocktail-text-wrapper > h1'),
    // modalCocktailTextWrapperDarkH2: document.querySelector('.modal-cocktail-text-wrapper > h2'),
    // modalCocktailInstuctionDark: document.querySelector('.modal-cocktail-instuction'),
    // modalCocktailInstuctionTextDark: document.querySelector('.modal-cocktail-instuction-text'),
    // ingredientListItemDark: document.querySelector('.ingredient-list-item'),
    // ingNameDark: document.querySelector('.ing-name'),
    // cocktailNameDark: document.querySelector('.cocktail-name'),
    // ingDesModalDark: document.querySelector('.ing-des-modal'),
    // ingDesModalDark: document.querySelector('.ing-info-item'),
    // cocktailsItemDark: document.querySelector('.cocktails-item'),
    body: document.querySelector('body'),
}